on:
    workflow_dispatch:
        
jobs:
    build-release:
        runs-on: self-hosted
        name: test action
        steps:             
        
          #- name: Install dependencies
          #  run: |
          #       sudo apt update && \
          #       sudo apt install -y git python3 && \
          #       sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libusb-1.0-0-dev                            

          # - name: Check out this repository with submodules
          #   uses: actions/checkout@v2
          #   with:
          #       submodules: recursive
          
          - name: misc tests
            run: |
                 arm-none-eabi-gcc --version
                 id -u
                 export PICO_SDK_PATH="$HOME/pico-sdk"
                 echo "$PICO_SDK_PATH"
                 ls -l
                 echo "$PICO_SDK_PATH"
              
